### ISSUE TITLE
Background colors changed

### ISSUE THREAD

**Issue by tusing** [ntwb/posh-monokai#5]
Hi!

I merged the registry files, but the background color has been changed. I only want the text color to change - is there a way to undo this, or change it so only the text colors change?

Thanks!

**Comment by ntwb** [comment]
The settings in this repo include changing the background colour.

I'd suggest taking a look at these repo's as I'd recommend these over my repo these days:

In particular https://github.com/lukesampson/concfg and https://github.com/lukesampson/pshazz

Also https://github.com/lukesampson/scoop and https://github.com/lukesampson/scoop-extras
