### ISSUE TITLE
More clarity on installation instructions

### ISSUE THREAD

**Issue by connerk** [ntwb/posh-monokai#8]
Two of the install instructions are
```
Merge the HKCU-Console.reg registry file to register the Monokai colours for PowerShell.

Merge the register-console-font.reg registry file to register Adobe Source Code Pro as a 'console' font.
```
can you define what it means to merge a registry file? 
these instructions assume the user knows how to do this instead of instructing how to do it.

**Comment by ntwb** [comment]
I'm not using Windows anymore and can't really help other than to say Microsoft has docs for this, make sure you also backup the registry before you make the changes.
